import { useEffect, useState } from "react";
import { Check, Plus, Tag, X } from "lucide-react";

const priorities = ["None", "Low", "Medium", "High", "Urgent"];

export function TaskDrawer({ project, task, onClose, onSave, onToggleChecklistItem, onCreateChecklistItem }) {
  const [draft, setDraft] = useState(task); const [newItem, setNewItem] = useState("");
  useEffect(() => setDraft(task), [task]);
  const update = (patch) => setDraft((current) => ({ ...current, ...patch }));
  const save = async (patch = draft) => onSave(task.id, patch);
  const toggleChecklist = async (itemId) => { const item = draft.checklist.find((entry) => entry.id === itemId); const checklist = draft.checklist.map((entry) => entry.id === itemId ? { ...entry, done: !entry.done } : entry); update({ checklist }); await onToggleChecklistItem(item); };
  const addItem = async (event) => { event.preventDefault(); if (!newItem.trim()) return; await onCreateChecklistItem(task.id, newItem.trim()); setNewItem(""); };
  const toggleLabel = (labelId) => { const labelIds = draft.labelIds.includes(labelId) ? draft.labelIds.filter((id) => id !== labelId) : [...draft.labelIds, labelId]; update({ labelIds }); save({ labelIds }); };
  const completed = draft.checklist.filter((item) => item.done).length;
  return <aside className="drawer"><div className="drawer-top"><span className="drawer-kicker">Task details</span><button className="icon-button" onClick={onClose} aria-label="Close task details"><X size={19} /></button></div><input className="drawer-title" value={draft.title} onChange={(event) => update({ title: event.target.value })} onBlur={() => save()} aria-label="Task title" /><div className="field-grid"><label>Status<select value={draft.columnId} onChange={(event) => { update({ columnId: event.target.value }); save({ columnId: event.target.value }); }}>{project.columns.map((column) => <option key={column.id} value={column.id}>{column.name}</option>)}</select></label><label>Priority<select value={draft.priority} onChange={(event) => { update({ priority: event.target.value }); save({ priority: event.target.value }); }}>{priorities.map((priority) => <option key={priority}>{priority}</option>)}</select></label><label>Story points<input type="number" min="0" value={draft.points ?? ""} onChange={(event) => update({ points: event.target.value ? Number(event.target.value) : null })} onBlur={() => save()} /></label><label>Due date<input type="date" value={draft.dueDate} onChange={(event) => { update({ dueDate: event.target.value }); save({ dueDate: event.target.value }); }} /></label></div><section className="drawer-section"><h3><Tag size={16} /> Labels</h3><div className="label-picker">{project.labels.length ? project.labels.map((label) => <button key={label.id} className={`label label-${label.colour} ${draft.labelIds.includes(label.id) ? "chosen" : ""}`} onClick={() => toggleLabel(label.id)}>{draft.labelIds.includes(label.id) && <Check size={12} />}{label.name}</button>) : <span className="muted">No labels in this project.</span>}</div></section><section className="drawer-section"><h3>Description</h3><textarea className="description" value={draft.description} onChange={(event) => update({ description: event.target.value })} onBlur={() => save()} placeholder="Add a more detailed description…" /></section><section className="drawer-section"><div className="section-title"><h3>Checklist</h3><span>{completed} / {draft.checklist.length}</span></div>{draft.checklist.map((item) => <label className="check-item" key={item.id}><input type="checkbox" checked={item.done} onChange={() => toggleChecklist(item.id)} /><span>{item.title}</span></label>)}<form className="new-check" onSubmit={addItem}><input value={newItem} onChange={(event) => setNewItem(event.target.value)} placeholder="Add an item" /><button aria-label="Add checklist item"><Plus size={16} /></button></form></section><div className="saved"><Check size={14} /> Saved</div></aside>;
}
